config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  resources :tasks
  get 'home' => 'home#show'
  get '/' => 'home#show'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  paginates_per 10
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.order(created_at: :desc).page(params[:page]).per(params[:per])
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to favorites_path }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to favorites_path }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_favorite
    @favorite = Favorite.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def favorite_params
    params.require(:favorite).permit(:name, :language, :url, :about)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    data = HTTP.get('https://voucomerno.ru/').to_s
    @card = ActionController::Base.helpers.strip_tags(data)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all.sort_by { |e| e[:dead_line] }
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:name, :level, :done, :dead_line, :about)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(controller_name)
    controller.controller_name == controller_name ? 'active' : ''
  end
end

app/helpers/favorites_helper.rb
# Favorites Helper
module FavoritesHelper
  def icon_path(language = 'default')
    case language.downcase
    when 'python'
      return image_path('favorites/python.svg')
    when 'ruby'
      return image_path('favorites/ruby.svg')
    when 'html'
      return image_path('favorites/html.svg')
    when 'css'
      return image_path('favorites/css.svg')
    when 'java'
      return image_path('favorites/java.svg')
    when 'javascript'
      return image_path('favorites/javascript.svg')
    when 'php'
      return image_path('favorites/php.svg')
    when 'hack'
      return image_path('favorites/hack.svg')
    when 'go'
      return image_path('favorites/go.svg')
    when 'linux'
      return image_path('favorites/linux.svg')
    when 'c++'
      return image_path('favorites/cpp.svg')
    else
      return image_path('favorites/default.svg')
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
# Task Helper
module TasksHelper
  def done_icon(done)
    done ? 'ok' : 'remove'
  end
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite, class: "form-horizontal") do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: :name %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control", placeholder: :url %>
  </div>
  <div class="form-group">
    <%= f.label :language %><br>
    <%= f.text_field :language, class: "form-control", placeholder: :language %>
  </div>
  <div class="form-group">
    <%= f.label :about %><br>
    <%= f.text_area :about, class: "form-control", placeholder: :about %>
  </div>
  <div class="form-group btn-group">
    <%= link_to 'Back', favorites_path, class: "btn btn-primary" %>
    <%= f.submit 'Submit', class: "btn btn-success"%>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h3>Edit Favorite</h3></div>
    <div class="panel-body">
      <div class="form-container">

        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h3><span class="glyphicon glyphicon-star" aria-hidden="true"></span> Favorites</h3></div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Url</th>
          <th>Language</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @favorites.each do |favorite| %>
        <tr>
          <td><%= favorite.name %></td>
          <td><a target="_blank" href="<%= favorite.url %>"><%= favorite.url %></a></td>
          <td><img alt="My Radmin Panel" src="<%= icon_path(favorite.language) %>" width="35px"></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to 'Edit', edit_favorite_path(favorite), class: "btn btn-warning" %>
              <%= link_to 'Show', favorite, class: "btn btn-info" %>
              <%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Create Favorite', new_favorite_path, class: "btn btn-success" %>
  </div>
</div>
<div class="row">
  <div class="text-center">
    <%= paginate @favorites %>
  </div>
</div>
<br>

app/views/favorites/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h3>New Task</h3></div>
    <div class="panel-body">
      <div class="form-container">

        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/favorites/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h3>Id: <%= @favorite.id %></h3></div>
    <div class="panel-body">
      <ul class="list-group">
      <li class="list-group-item">
        <strong>Name:</strong>
        <%= @favorite.name %>
      </li>

      <li class="list-group-item">
        <strong>Url:</strong>
        <a target="_blank" href="<%= @favorite.url %>"><%= @favorite.url %></a>
      </li>

      <li class="list-group-item">
        <strong>Language:</strong>
        <%= @favorite.language %>
      </li>

      <li class="list-group-item">
        <strong>About:</strong>
        <%= @favorite.about %>
      </li>
    </ul>
      <div class="form-group btn-group">
        <%= link_to 'Back', favorites_path, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_favorite_path(@favorite), class: "btn btn-warning"%>
      </div>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<div class="row">
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <p><strong>Cardápio</strong></p>
      <code><%= @card %></code>
    </a>
  </div>
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <img src="http://www.image-mapper.com/photos/original/missing.png?1263880893" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <img src="http://www.image-mapper.com/photos/original/missing.png?1263880893" alt="...">
    </a>
  </div>
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <img src="http://www.image-mapper.com/photos/original/missing.png?1263880893" alt="...">
    </a>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" id = "navbar_icon_home" href="/home">
        <img alt="Home" src="/home">
      </a>
      <a class="navbar-brand" id = "navbar_icon_media" href="https://github.com/" target="_blank">
        <img alt="My Radmin Panel" src="<%= image_path("social-icons/git.svg") %>" width="35px">
      </a>
      <a class="navbar-brand" id = "navbar_icon_media" href="https://inbox.google.com/" target="_blank">
        <img alt="My Radmin Panel" src="<%= image_path("social-icons/email.svg") %>" width="35px">
      </a>
      <a class="navbar-brand" id = "navbar_icon_media" href="https://moodle.ufsc.br/" target="_blank">
        <img alt="My Radmin Panel" src="<%= image_path("social-icons/school.svg") %>" width="35px">
      </a>
      <a class="navbar-brand" id = "navbar_icon_media" href="http://discourse.sumone.com.br" target="_blank">
        <img alt="My Radmin Panel" src="<%= image_path("social-icons/people.svg") %>" width="35px">
      </a>
      <a class="navbar-brand" id = "navbar_icon_media" href="https://www.facebook.com/" target="_blank">
        <img alt="My Radmin Panel" src="<%= image_path("social-icons/face.svg") %>" width="35px">
      </a>
      <a class="navbar-brand" id = "navbar_icon_media" href="https://www.instagram.com/" target="_blank">
        <img alt="My Radmin Panel" src="<%= image_path("social-icons/twitter.svg") %>" width="35px">
      </a>
      <a class="navbar-brand" id = "navbar_icon_media" href="https://www.instagram.com/" target="_blank">
        <img alt="My Radmin Panel" src="<%= image_path("social-icons/instagram.svg") %>" width="35px">
      </a>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div id="sidebar_div">
  <ul class="nav nav-pills nav-stacked">
    <li role="presentation" class="<%= active_class('home') %>">
      <a href="/home"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a>
    </li>
    <li role="presentation" class="<%= active_class('school') %>">
      <a href="/schools"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> School</a>
    </li>
    <li role="presentation" class="<%= active_class('tasks') %>">
      <a href="/tasks"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Tasks</a>
    </li>
    <li role="presentation" class="<%= active_class('favorites') %>">
      <a href="/favorites"><span class="glyphicon glyphicon-star" aria-hidden="true"></span> Favorites</a>
    </li>
    <li role="presentation" class="<%= active_class('bills') %>">
      <a href="/bills"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span> Bills</a>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Radmin</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <link href="app/assets/stylesheets/application.css" rel="stylesheet">
</head>
<body>

  <%= render 'layouts/navbar' %>

  <%= render 'layouts/sidebar' %>

  <div class="main_container">
    <div class="main_content">
      <%= yield %>
    </div>
  </div>

</body>

app/views/tasks/_form.html.erb
<%= form_for(@task, class: "form-horizontal") do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: :name%>
  </div>
  <div class="form-group input-group">
    <%= f.label :level %><br>
    <%= f.number_field :level, class: "form-control", placeholder: :level %>
  </div>
  <div class="form-group">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="form-group">
    <%= f.label :dead_line %><br>
    <div class='input-group date' id='datetimepicker1'>
      <%= f.text_field :dead_line, class: "form-control", placeholder: :dead_line %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
    <script type="text/javascript">
      $(function () {
        $('#datetimepicker1').datetimepicker();
      });
    </script>
  </div>
  <div class="form-group">
    <%= f.label :about %><br>
    <%= f.text_area :about, class: "form-control", placeholder: :about %>
  </div>
  <div class="form-group btn-group">
    <%= link_to 'Back', tasks_path, class: "btn btn-primary" %>
    <%= f.submit 'Submit', class: "btn btn-success"%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h3>New Task</h3></div>
    <div class="panel-body">
      <div class="form-container">

        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h3><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Tasks</h3></div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Level</th>
          <th>Dead line</th>
          <th>Done</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td><%= task.name %></td>
            <td><%= task.level %></td>
            <td><%= task.dead_line %></td>
            <td><span class="glyphicon glyphicon-<%= done_icon(task.done) %>" aria-hidden="true"></span></td>
            <td>
              <div class="btn-group" role="group">
                <%= link_to 'Edit', edit_task_path(task), class: "btn btn-warning" %>
                <%= link_to 'Show', task, class: "btn btn-info" %>
                <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-danger" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Create Task', new_task_path, class: "btn btn-success" %>
  </div>
</div>
<br>

app/views/tasks/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h3>New Task</h3></div>
    <div class="panel-body">
      <div class="form-container">

        <%= render 'form' %>
        
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><h3>Id: <%= @task.id %></h3></div>
    <div class="panel-body">
      <ul class="list-group">
      <li class="list-group-item">
        <strong>Name:</strong>
        <%= @task.name %>
      </li>

      <li class="list-group-item">
        <strong>Level:</strong>
        <%= @task.level %>
      </li>

      <li class="list-group-item">
        <strong>Done:</strong>
        <%= @task.done %>
      </li>

      <li class="list-group-item">
        <strong>Dead line:</strong>
        <%= @task.dead_line %>
      </li>

      <li class="list-group-item">
        <strong>About:</strong>
        <%= @task.about %>
      </li>
    </ul>
      <div class="form-group btn-group">
        <%= link_to 'Back', tasks_path, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_task_path(@task), class: "btn btn-warning"%>
      </div>
    </div>
  </div>
</div>